spring.application.name=backend
# 1. URL de conexión a la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db

# 2. Credenciales
spring.datasource.username=postgres
spring.datasource.password=1234

# 3. Crea o actualiza las tablas automáticamente al dar "Play"
spring.jpa.hibernate.ddl-auto=update

# 4. Muestra en la consola el SQL real que Java genera por abajo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true